# http://docs.travis-ci.com/user/languages/objective-c/
# https://github.com/facebook/xctool

language: objective-c

osx_image: xcode7

# xcode_project: SampleNotifcations/SampleNotifcations.xcodeproj
# xcode_workspace: SampleNotifcations/SampleNotifcations.xcworkspace

# xcode_scheme: SampleNotifcationsTests

podfile: SampleNotifcations/Podfile

# xcode_sdk: iphonesimulator9.0

script:
 
  xctool
  -workspace SampleNotifcations/SampleNotifcations.xcworkspace
  -scheme SampleNotifcationsTests
  -sdk iphonesimulator
  build 
  test
  ONLY_ACTIVE_ARCH=NO
  CODE_SIGN_IDENTITY=""
  CODE_SIGNING_REQUIRED=NO

notifications:
  email: false

before_install:
  - brew update
  - brew uninstall xctool && brew install --HEAD xctool
